### ISSUE TITLE
Peer to Peer Code Review.

### ISSUE THREAD

**Issue by IsmailChangezi** [PrantoshB/Leaderboard#5]
Hello @PrantoshB , 
Good job on meeting all the requirements 🥇 
I have checked your project and there is nothing else to say that it is complete.
The designs are looking so good you have done a pretty good job 
That's it.
Best of luck with your future projects 💐 
and
Happy Coding 👨🏻‍💻

**Comment by PrantoshB** [comment]
Hello @IsmailChangezi, thanks for this beautiful comment. ❤

Have a good day 👨🏽‍💻
